--- #YAML:1.0
name:               Image-GeoTIFF-Tiled
version:            0.05
abstract:           A Perl interface to libgeotiff for reading tiled TIFF images, with support for extracting and iterating arbitrary shapes.
author:
    - Blake Willmarth <bwillmarth@gmail.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Inline:           0.44
    List::MoreUtils:  0.16
    Module::Load:     0.16
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
